### ISSUE TITLE
Wrong email when creating kubeconfig

### ISSUE THREAD

**Issue by thokra-nav** [nais/narcos#31]
If you have logged in to `gcloud` with multiple emails, the generated kubeconfig uses whichever email is sorted last.

Should we change the email retrieval logic to use the current active user account in gcloud?

**Comment by Kyrremann** [comment]
Hørtes ut som en bug, den burde bruke nais.no-adressen din, for er kun den som har tilgang. For `seperateAdmin` vil den bruke nav-adressen.
