### ISSUE TITLE
Support for nais-io cluster

### ISSUE THREAD

**Issue by jhrv** [nais/narcos#40]
Running `narc cluster kubeconfig` should also fetch the cluster in `nais-io`

**Comment by Kyrremann** [comment]
Hvilke clustere savner du? Tok en kjapp titt i nais.io og dev-nais.io orgen og så ingenting der. Har ikke tilgang til nais-io orgen.

Disse får jeg listet opp:
```ci-fss
ci-gcp-nais
dev-fss
dev-gcp
dev-gcp-nais
dev-nais-ci
dev-nais-dev
dev-nais-management-v2
knada
mtpilot-dev
mtpilot-management-v2
mtpilot-prod
nais-management-v2
prod-fss
prod-gcp
prod-gcp-nais
ssb-management-v2
ssb-prod
ssb-staging```
